### ISSUE TITLE
initdb: error: directory "/var/lib/postgresql/data" exists but is not empty

### ISSUE THREAD

**Issue by timvol** [reactive-tech/kubegres#11]
I followed the getting-started tutorial and got the following yaml:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
spec:
   replicas: 2
   image: postgres:13.2

   database:
      size: 200Mi
      storageClassName: csi-cinder-high-speed

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
```

But I'm getting the following error message:

> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "en_US.utf8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
> It contains a lost+found directory, perhaps due to it being a mount point.
> Using a mount point directly as the data directory is not recommended.
> Create a subdirectory under the mount point.

Any idea how I can fix this issue?

**Comment by timvol** [comment]
Hi @alex-arica,

thank ou very much for your response.
Unfortunately it doesn't help. It shows me the same error message but with another path:

> The files belonging to this database system will be owned by user "postgres".
> This user must also own the server process.
> 
> The database cluster will be initialized with locale "en_US.utf8".
> The default database encoding has accordingly been set to "UTF8".
> The default text search configuration will be set to "english".
> 
> Data page checksums are disabled.
> 
> initdb: error: directory "/var/lib/postgresql/data/db" exists but is not empty
> It contains a lost+found directory, perhaps due to it being a mount point.
> Using a mount point directly as the data directory is not recommended.
> Create a subdirectory under the mount point.

**Comment by alex-arica** [comment]
Investigating.

**Comment by alex-arica** [comment]
I released a new version of Kubegres v1.2

Could you please reinstall Kubegres and let me know if it works for you?

Installation:
```kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.2/kubegres.yaml```


And please run your initial YAML:
```
...
database:
   size: 200Mi
   storageClassName: csi-cinder-high-speed
```

You do not need to specify "volumeMount".
