### ISSUE TITLE
Help required in connecting to DB from inside and outside of Kubernetes

### ISSUE THREAD

**Issue by dralquinta** [reactive-tech/kubegres#120]
Hi, 

Upon creating the pgsql database with the operator, then the following appears on the services: 

![image](https://user-images.githubusercontent.com/51421891/175697732-2ce30001-587c-4fa0-990c-f1ccaa49fb2c.png)

As seen, no IP address is binded into pgsqldb service, which prevents me to do anything with the DB in the first place.

I then, went ahead and dug into some issues opened Ref: https://github.com/reactive-tech/kubegres/issues/74 and https://github.com/reactive-tech/kubegres/issues/46 which suggested somehow to create a ingress Service as this one: 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: pgsqlservice
  namespace: pgdatabase
  labels:
    app: pgsqldb
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: pgsqldb
```

This ended up creating a service ip as seen here: 

![image](https://user-images.githubusercontent.com/51421891/175697944-d47f8114-db8f-4ade-9e9d-cd99e9f2fb18.png)

However when trying to use that for anything I need, it simply doesn't work. 

I'm pretty sure this is something that I'm doing wrong, however I'll appreciate if some of you can clarify how can I connect to the DB. This is related to a ruby on rails impl, which without Postgresql database, renders the app useless. 

Side note: 

When trying to do a lookup from ruby pod, this is what it's returned: 

```shell
root@app-deployment-7f959f7f8d-wql2r:/app# telnet pgsqlservice 5432
telnet: could not resolve pgsqlservice/5432: Name or service not known

root@app-deployment-7f959f7f8d-wql2r:/app# telnet pgsqldb 5432
telnet: could not resolve pgsqldb/5432: Name or service not known
```

None of the IPs will return to ping neither.
