### ISSUE TITLE
Unable to promote last remaining pod

### ISSUE THREAD

**Issue by 2fst4u** [reactive-tech/kubegres#124]
I somehow managed to have my cluster silently break overnight and only one of my 3 kubegres pods is running, but it wasn't the primary. I have gone through the instructions to promote it forcefully but it seems it won't as it keeps looking for the current primary.

This seems like an oversight since the only reason you'd want to forcefully failover is when the primary isn't available.

Is there anything I can do to make the remaining version the primary? I can't retrieve the lost data but that's fine, I don't need it as badly as I need a working database at all.

**Comment by 2fst4u** [comment]
The "status" part of my kubegres CRD states the following:

```
status:
  blockingOperation:
    operationId: Primary DB count spec enforcement
    statefulSetOperation:
      instanceIndex: 11
      name: postgres-11
    statefulSetSpecUpdateOperation: {}
    stepId: Failing over by promoting a Replica DB as a Primary DB
    timeOutEpocInSeconds: 1657330727
  enforcedReplicas: 8
  lastCreatedInstanceIndex: 12
  previousBlockingOperation:
    hasTimedOut: true
    operationId: Primary DB count spec enforcement
    statefulSetOperation:
      instanceIndex: 11
      name: postgres-11
    statefulSetSpecUpdateOperation: {}
    stepId: Waiting few seconds before failing over by promoting a Replica DB as a
      Primary DB
    timeOutEpocInSeconds: 1657330426

```

So it looks like it's attempting the failover but something is stopping it.
