### ISSUE TITLE
No pod, sts created in default namespace

### ISSUE THREAD

**Issue by khteh** [reactive-tech/kubegres#130]
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: postgresql
  namespace: default 
spec:
   replicas: 2
   image: postgres:latest
   database:
      size: 200Mi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgresql-secret
              key: superUserPassword
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: postgresql-secret
              key: replicationUserPassword
```
```
$ kubectl apply -f postgresql.yml
kubegres.kubegres.reactive-tech.io/postgresql unchanged
```
