### ISSUE TITLE
Adding custom annotations?

### ISSUE THREAD

**Issue by laukaichung** [reactive-tech/kubegres#14]
I want to use Linkerd and Bank Vault with Kubegres. But `Kubegres` doesn't seem to support custom annotations.  Would you consider this feature?

if adding custom annotations is supported, I'd use Vault to inject secrets into the environment without relying on creating a secret. But right now it looks like replica pods would fail to start without `valueFrom.secretKeyRef`. It keeps asking `Password` in the logs.

````
spec:
  env:
    - name: POSTGRES_PASSWORD
      value: gffdggfdgfdf (Would use #vault:secret/data/path#DB_PASSWORD if custom annotations can be used)

    - name: POSTGRES_REPLICATION_PASSWORD
      value: fgdgfdgdffd
````

**Comment by alex-arica** [comment]
Thank you for your enhancement suggestion. 

When you use:
annotations:
    linkerd.io/inject: enabled

Do you set it from a StatefulSet? Or from another resources so that it is applied to your Pod?

Do you have an example?

**Comment by laukaichung** [comment]
Thank you alex! Looking forward to use this operator. Goodbye Zalando...

**Comment by alex-arica** [comment]
Thanks for your kind feedback about Kubegres.  I agree and we are planning to keep Kubegres simple.

I made a change and manually I tested it locally. I pushed the changes in GIT main so that I can get your feedback.  

Could you please test it for me as well?

Once you confirm that it is working, I am going to update the acceptance tests and create a release.

Please reinstall the Kubegres controller as follows:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

The above installation YAML is directly from GIT main. 

You can add your annotation(s) from the YAML of "kind: Kubegres". 

Please see an example below:

```
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
  annotations:
    linkerd.io/inject: enabled
```
