### ISSUE TITLE
Specific nodeAffinity to only primary

### ISSUE THREAD

**Issue by bastoune** [reactive-tech/kubegres#157]
Hello,

Hi would like to update the Kubegres statefulSet, but only the primary one.
Is it possible from the `kubegres.reactive-tech.io/v1` resource ?

Basically, i would like to apply this spec:
```
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: k8s.scaleway.com/dedicated-cpu
                operator: In
                values:
                - "true"
                ```

I want to keep the fact the replicats are in PodAntiAffinity with the Primary. But i want the primary to prefer being deployed on the `k8s.scaleway.com/dedicated-cpu` labelled node.
