### ISSUE TITLE
"storageClassName" definition doesn't work.

### ISSUE THREAD

**Issue by behniafb** [reactive-tech/kubegres#164]
As you can see in my Kubegres.yaml config below, I've set the storageClass to be "local-path":
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
spec:
  replicas: {{ .Values.database.replicaCount }}
  image: postgres:14.1

  database:
    size: 5Gi
    storageClassName: local-path

  backup:
    # Backup every 12 hours
    schedule: "0 */12 * * *"
    pvcName: my-backup-pvc
    volumeMount: /var/lib/backup

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-database-secret
          key: PASSWORD

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-database-secret
          key: REPLICATION_USER_PASSWORD

```

BUT when it deploys, and creates the related PVC, I see that the storageClass is set to "local-storage" instead of "local-path":

postgres-db-mypostgres-1-0 PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: '2023-10-23T13:18:17Z'
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: mypostgres
    index: '1'
  name: postgres-db-mypostgres-1-0
  namespace: sdk
  resourceVersion: '846624'
  uid: 553aba82-334a-4a0f-b43b-c713a82713d3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeMode: Filesystem
status:
  phase: Pending
```

SO -> it's always requesting for that SC, which doesn't exist, and because I'm on bare-metal and I don't have any cloud storage provisioned, the database can't deploy, and produces error:
- postgres-db-mypostgres-1-0 (PVC) event log:
```
ProvisioningFailed
storageclass.storage.k8s.io "local-storage" not found
```
- mypostgres-1-0 (pod) event log:
```
LAST SEEN   TYPE      REASON             OBJECT               MESSAGE
25m         Warning   FailedScheduling   pod/mypostgres-1-0   0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1                                nodes are available: 1 Preemption is not helpful for scheduling..
```

My k8s cluster is on bare-metal.
