### ISSUE TITLE
Node scheduling

### ISSUE THREAD

**Issue by keithpenrod** [reactive-tech/kubegres#17]
Is it possible to specify node scheduling parameters? For example, if I want to ensure the pods schedule on on-demand nodes (instead of spot nodes) or if I want to add a toleration so it's able to schedule on a node with a taint.

**Comment by alex-arica** [comment]
Thank you for your message and your suggestion.

Currently Kubegres add the following rules:
```
affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - postgres-name
                topologyKey: "kubernetes.io/hostname"
```

We could allow overriding the field "affinity" from a YAML configuring a cluster of PostgreSql (YAML of "kind :Kubegres").

If you had to add your own rules in a StatefulSet resource, what would they be in term of YAML example?

**Comment by keithpenrod** [comment]
I manually edited the stateful sets that kubegres created to include the following under "spec:"

```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instanceclass
                operator: In
                values:
                - on-demand
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - document-store
              topologyKey: kubernetes.io/hostname
            weight: 100
      tolerations:
      - key: group
        operator: Equal
        value: critical
```
So I left the podAntiAffinity that kubegres created and added the nodeAffinity and tolerations. A way to specify tolerations and either nodeAffinity or nodeSelector would be nice. 
Just for a bit of background, I'm deploying in an AWS cluster so I'd prefer to schedule on an on-demand node instead of a spot instance for greater stability and I have nodes that are tainted for usage only with critical systems and would like to allow kubegres to schedule on them.

**Comment by keithpenrod** [comment]
Yeah that sounds perfect. Thank you.

**Comment by LahiruSenevirathne** [comment]
> I manually edited the stateful sets that kubegres created to include the following under "spec:"
> 
> ```
>       affinity:
>         nodeAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>             nodeSelectorTerms:
>             - matchExpressions:
>               - key: instanceclass
>                 operator: In
>                 values:
>                 - on-demand
>         podAntiAffinity:
>           preferredDuringSchedulingIgnoredDuringExecution:
>           - podAffinityTerm:
>               labelSelector:
>                 matchExpressions:
>                 - key: app
>                   operator: In
>                   values:
>                   - document-store
>               topologyKey: kubernetes.io/hostname
>             weight: 100
>       tolerations:
>       - key: group
>         operator: Equal
>         value: critical
> ```
> 
> So I left the podAntiAffinity that kubegres created and added the nodeAffinity and tolerations. A way to specify tolerations and either nodeAffinity or nodeSelector would be nice.
> Just for a bit of background, I'm deploying in an AWS cluster so I'd prefer to schedule on an on-demand node instead of a spot instance for greater stability and I have nodes that are tainted for usage only with critical systems and would like to allow kubegres to schedule on them.

How did you do this each time edit the statefulset a new statefulset is created

**Comment by keithpenrod** [comment]
> 
> How did you do this each time edit the statefulset a new statefulset is created

Yeah. I just did kubectl edit sts on each of the replicas (I only had 3 replicas so it wasn't too cumbersome).

**Comment by sshekghub** [comment]
Hi Alex, did you get a chance to work on this requirement ? Any rough estimate by when you will be able to release this ? Thanks
Regards
SS

**Comment by alex-arica** [comment]
Hi, thank you for your message.
I will start working on it next week, on Friday.

**Comment by sshekghub** [comment]
> Hi, thank you for your message.
> I will start working on it next week, on Friday.

Thank you for the update, Alex. Appreciate it ! 
Regards SS

**Comment by alex-arica** [comment]
Kubegres version 1.9 has a new field "scheduler" under which you can add the fields "affinity" and/or "tolerations". 

For example:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:

   replicas: 3
   image: postgres:13.2

   database:
      size: 200Mi
      storageClassName: standard
   
   scheduler:
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
             - matchExpressions:
               - key: instanceclass
                 operator: In
                 values:
                 - on-demand
         podAntiAffinity:
           preferredDuringSchedulingIgnoredDuringExecution:
           - podAffinityTerm:
               labelSelector:
                 matchExpressions:
                 - key: app
                   operator: In
                   values:
                   - document-store
               topologyKey: kubernetes.io/hostname
             weight: 100
   
       tolerations:
       - key: group
         operator: Equal
         value: critical

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
```
I wrote acceptances tests for this feature. It is working fine. Could you please test it and let me know if you are happy with it?

To install the new version:

```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.9/kubegres.yaml
```

Please let me know.
