### ISSUE TITLE
unknown field "spec.volume.volumeClaimTemplates.name"

### ISSUE THREAD

**Issue by nikolaiorda** [reactive-tech/kubegres#170]
Hello,

I'm trying to apply custom settings with volumeClaimTemplates option from this doc: https://www.kubegres.io/doc/properties-explained.html
However, it does not work even with the example from that link. The error below:
```
kubectl apply -f my-postgres.yaml
Error from server (BadRequest): error when creating "my-postgres.yaml": Kubegres in version "v1" cannot be handled as a Kubegres: strict decoding error: unknown field "spec.volume.volumeClaimTemplates.name", unknown field "spec.volume.volumeClaimTemplates.spec"
```
To test it, just follow steps from "Getting started" and add the volume section from the "All properties explained" article. All settings are default.
Is it a bug or the documentation is outdated?
Thank you in advance.

**Comment by alex-arica** [comment]
Hi,
Let me help me with this. 
Could you please share the contents of the YAML that you tried to apply with kubectl ?

**Comment by nikolaiorda** [comment]
Sure! Here you go:
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:

   replicas: 3
   image: postgres:16.1

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword

   volume:

      volumeClaimTemplates:
         name: anyMount
         spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-storage
            resources:
              requests:
                storage: 1Gi
```
I was trying it woth "volumes" and "volumeMounts" before as well as with different paths and replacing anyMount with any other value. The result was always the same.

**Comment by alex-arica** [comment]
You find an issue in the documentation. Thank you :)

I updated the doc and released the changes: https://www.kubegres.io/doc/properties-explained.html

Try the following, by adding the field "name" under "metadata":

```
   volume:

      volumeClaimTemplates:
        - metadata:
            name: anyMount
         spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-storage
            resources:
              requests:
                storage: 1Gi
```

**Comment by nikolaiorda** [comment]
Thank you for your reply! Let's try to apply it:
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:

   replicas: 3
   image: postgres:16.1

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword

   volume:

      volumeClaimTemplates:
        - metadata:
            name: anyMount
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: local-storage
            resources:
              requests:
                storage: 1Gi
```
(The indentation from the example above may not be accurate due to copying and pasting. I formatted it in a correct way on my lab environment)
And the result is the following:
```
kubectl apply -f my-postgres.yaml
Error from server (BadRequest): error when creating "my-postgres.yaml": Kubegres in version "v1" cannot be handled as a Kubegres: strict decoding error: unknown field "spec.volume.volumeClaimTemplates[0].metadata"
```

**Comment by alex-arica** [comment]
Oh you know what, it seems like the initial example in the documentation was correct. I did not notice in your initial YAML example that "-" was missing.
Could you please try as below?

For us it works fine.

```
   volume:

      volumeClaimTemplates:
        - name: anyMount
          spec:
             accessModes: [ "ReadWriteOnce" ]
             storageClassName: local-storage
             resources:
               requests:
                 storage: 1Gi
```
