### ISSUE TITLE
[SPEC] Add Support for resource requests / limits

### ISSUE THREAD

**Issue by shubhamranjan** [reactive-tech/kubegres#22]
Currently, the deployed pods don't have any resource requests/limits assigned to them and currently there is no way to add the same via specs.

A possible way to do the same in the following format:

```
spec.primary.resources.limits.cpu
spec.primary.resources.limits.memory
spec.primary.resources.requests.cpu
spec.primary.resources.requests.memory

spec.replica.resources.limits.cpu
spec.replica.resources.limits.memory
spec.replica.resources.requests.cpu
spec.replica.resources.requests.memory
```

Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

**Comment by alex-arica** [comment]
Hello. 
Thank you for your feature suggestion. It is a great idea.
I added it in the backlog of Kubegres. I will use this issue when committing and releasing it.

**Comment by alex-arica** [comment]
Are you still interested in this feature?

What would you suggest that we add as field(s) in Kubegres YAML when creating a cluster of PostgreSql instances?

**Comment by shubhamranjan** [comment]
@alex-arica  Thanks for following up. Yes, I am still interested in this.  As described in the proposal above, a sample would look something like this:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13

  database:
    size: 1Gi
    storageClassName: do-block-storage

  primary:
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"

  replica:
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgsql-secret
          key: replicationUserPassword

```

where primary refers to the primary node and replica refers to the replica nodes. Any further config additions w.r.t primary/replica nodes can be added under these respective  props.

**Comment by alex-arica** [comment]
Thank you for the YAML example. This feature is in the backlog and will be implemented at some stage.

**Comment by ylck** [comment]
@alex-arica Can I implement it?

**Comment by alex-arica** [comment]
@ylck thank you for suggesting implementing it. That's absolutely fine with me.

Note that from Monday 13 September I am going to work for 2 weeks consecutively on Kubegres. Perhaps I may have time to implement this feature which is the 3rd most important feature in the backlog. But if meanwhile you would like to suggest a code changes, I will be also happy to review it.

**Comment by alex-arica** [comment]
I am going to allow setting resources for all Pods rather than allowing setting separate options for Primary or Replica pods.

The reason for this approach is, if a Replica is promoted as a Primary, it will be less risky to have Primary and Replica with the same resource requests/limit configuration. If for some reasons, there is not enough memory on the node where a Replica is promoted to a Primary, it may cause the failover process to fail. 

In the other hand, if we apply the same resources to Primary and Replica when the cluster is first created, that risk does not exist.

Please see below an example of how the YAML would look like:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13
...
  resourceRequirements:
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
      requests:
        memory: "2Gi"
        cpu: "1"
...
```

The above would apply to Primary and Replica Pods.
