### ISSUE TITLE
Add support to manage volumes from Kubegres YAML

### ISSUE THREAD

**Issue by patrickdung** [reactive-tech/kubegres#27]
By default, the docker image of official PostgreSQL only configure 64MB for /dev/shm (check the [Caveats section in Docker hub](https://hub.docker.com/_/postgres). It could cause problem for larger database.

```
# This is taken from the pod generated by Kubegres
Filesystem                  Size  Used Avail Use% Mounted on
shm                          64M   64K   64M   1% /dev/shm
```
There is one possible method, it is to increase the /dev/shm inside the container to be the same size as the host OS, default to 50% of RAM.
It is mentioned in [Stackoverflow](https://stackoverflow.com/questions/46085748/define-size-for-dev-shm-on-container-engine).

But currently, Kubegres Kind definition only allowed "volumeMount:". It would not recognize "volumes:" and "volumeMounts:", so it seems there is no way to increase the value for the shared memory.

**Comment by alex-arica** [comment]
Hi, thank you for your message.

I am going to add this as a new feature so that you can specify "volumes:" and "volumeMounts" in the Kubegres YAML.

**Comment by alex-arica** [comment]
Hello,

Are you still interested in this feature?

What would you suggest that we add as field(s) in Kubegres YAML when creating a cluster of PostgreSql instances?

**Comment by patrickdung** [comment]
Hello,

When using the default Docker image, we could use the setting mentioned in Stackoverflow. Below part is extracted from an existing deployment:

```
    spec:
      containers:
        - name: postgres
          .....
          env:
          .....
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: vol-pgsql01-data01
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: vol-pgsql01-data01
          persistentVolumeClaim:
            claimName: pvc-pgsql01
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: "600Mi"
```

The "sizeLimit" is enforced by eviction manager, it requires the feature gate 'LocalStorageCapacityIsolation' in the Kubernetes to be enabled (to be configured by user in their Kubernetes, not Kubegres). Related links: https://github.com/kubernetes/kubernetes/issues/63126#issuecomment-387817170 and https://github.com/kubernetes/enhancements/pull/1968

So for the Kubegres YAML, it should be able to support the "volumes" and "volumeMounts" directive. Then let the user configure their desired size for the SHM.

**Comment by alex-arica** [comment]
Thank you for your suggestion and the YAML example. This feature is in the backlog.

**Comment by rsaphala** [comment]
Any updates on this?

**Comment by alex-arica** [comment]
Thank you for your message.

We had priority requests from our clients who are paying a support subscription Kubegres. We always prioritised those requests as it allows us to sustain our team.

Since this is a request outside the support subscription, once I will have time, I will update this ticket.

**Comment by alex-arica** [comment]
I am ready to start working on this feature.

As a suggestion, in the YAML a new field "volume" could be:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13

  volume:

    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /dev/anything
        name: anyMount

    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "600Mi"

    volumeClaimTemplates:
      - metadata:
          name: anyMount
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard
          resources:
            requests:
            storage: 1Gi
...
```

It would be possible to create any volumes, volumeMounts and volumeClaimTemplates. However, I am not going to allow creating a volume on the Postgres data folder (/var/lib/postgresql/data) since it would override the default configuration in Kubegres and this could have implications. Let me know if this is a blocker.

So you could NOT do the following because it references Postgres data folder (/var/lib/postgresql/data):

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13

  volume:

    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: vol-pgsql01-data01

    volumes:
       - name: vol-pgsql01-data01
         persistentVolumeClaim:
           claimName: pvc-pgsql01
...
```

Please let me know about your thoughts.

**Comment by patrickdung** [comment]
Instead of exposing 'volumes' and 'volumeMounts' to users,
(afraid they would misuse it for local volume mount instead of using PVC with the Kubegres),
would it be good or possible to set dshm by using metadata/annotations or something like below?

A new directive for kind Kubegres, like:
```
  dshm:
     # or even omit 'name: dshm'?
     name: dshm
     sizeLimit: "600Mi"
```

which translate to these in the backend.

  volume:
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "600Mi"

Hey, I am not an expert on this area, it's just some of my thoughts.

**Comment by alex-arica** [comment]
Thank you for your suggestion. 

If that's what you need, I can add a new field "shmSize" under the existing "spec.database" as follows:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13

  database:
      size: 200Mi
      shmSize: 600Mi
      volumeMount: /var/lib/postgresql/data
...
```

Please let me know about your thoughts.

**Comment by patrickdung** [comment]
I think it looks good.
How about other people? Please give more comment / suggestion.

**Comment by alex-arica** [comment]
@Trolldemorted, @anneum @rsaphala any suggestions?

**Comment by anneum** [comment]
I like the suggestion to have the option create volumes, volumeMounts and volumeClaimTemplates.

**Comment by alex-arica** [comment]
@anneum thank you for your suggestion.

I share the same view that it would be more flexible to allow creating volumes, volumeMounts and volumeClaimTemplates from the YAML.

I started working on it this morning and it should be available by Tuesday 28 September.

**Comment by alex-arica** [comment]
I completed the changes locally. Today, I am writing acceptance tests and once it is completed I will be releasing a beta version in master. It would be either today or tomorrow morning.

**Comment by alex-arica** [comment]
The changes are available in the main branch as a version 1.11.  This is a beta version. 

The implementation is completed. I added few acceptance tests and tomorrow morning I will be adding additional tests.

Could you please help me by manually testing the changes? 

To install the beta version:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

You can test it by adding in your YAML fields such as volumes, volumeMounts and volumeClaimTemplates. Please see an example below:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: pgsql
  namespace: db

spec:
  replicas: 1
  image: postgres:13

  volume:

    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /dev/anything
        name: anyMount

    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "600Mi"

    volumeClaimTemplates:
      - metadata:
          name: anyMount
        spec:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: standard
          resources:
            requests:
            storage: 1Gi
```

If you are happy with your manual tests, please let me know. Once I got your feedback, I will be creating an official release of the version 1.11

Thank you!

**Comment by anneum** [comment]
Do I need the `volumeClaimTemplates` for the shm volume or is this config enough?
```
  volume:

    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
      - mountPath: /dev/anything
        name: anyMount

    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "600Mi"
```

**Comment by alex-arica** [comment]
"volumeClaimTemplates" is only required if you would like to use a storage class which will automatically create PVC and PV for you. And when "volumeClaimTemplates" is used, we don't need to use "volume".

The following configuration is sufficient to enable shm:

```
  volume:

    volumeMounts:
      - mountPath: /dev/shm
        name: dshm

    volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "600Mi"
```
