### ISSUE TITLE
Where does init_script.sh log to?

### ISSUE THREAD

**Issue by kahunacohen** [reactive-tech/kubegres#37]
I have added this to my Kubegres CRD (in `spec.customConfig`) to override the init_script.sh . I'd like to know if it's working. If I echo in the overridden script, where can I find the output? I tried looking at the pods' logs, and the CRD `Kubegres` doesn't have logs:

```yaml
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:
   replicas: 3
   image: postgres:13.2
   database:
      size: 200Mi
   customConfig: mypostgres-conf

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
```

In the ConfigMap `mypostgres-conf.yaml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mypostgres-conf
  namespace: default
data:
  primary_init_script.sh: |
    #!/bin/bash
    set -e
    
    # This script assumes that the env-var $POSTGRES_MY_DB_PASSWORD contains the password of the custom user to create.
    # You can add any env-var in your Kubegres resource config YAML.

    dt=$(date '+%d/%m/%Y %H:%M:%S');
    echo "$dt - Running init script the 1st time Primary PostgreSql container is created...";

    # customDatabaseName="my_app_db"
    # customUserName="my_username"

    # echo "$dt - Running: psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB ...";

    # psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    # CREATE DATABASE $customDatabaseName;
    # CREATE USER $customUserName WITH PASSWORD '$POSTGRES_MY_DB_PASSWORD';
    # GRANT ALL PRIVILEGES ON DATABASE "$customDatabaseName" to $customUserName;
    # EOSQL

    # echo "$dt - Init script is completed";
```

**Comment by kahunacohen** [comment]
Thanks for your response.

I don't see that the script was ever run. I started up everything from scratch, and query the logs of the primary postgres pod:

```
$ kubectl logs mypostgres-1-0 | grep 'Running init script'
$
```
I would expect to see "Running init script the 1st time Primary PostgreSql container is created" given the echo statement in the script in the configmap above...

**Comment by alex-arica** [comment]
I copied past the "kind: ConfigMap" and "kind: Kubegres" that you have provided and it worked for me. In the Primary Pod's logs I can see:
```
/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/primary_init_script.sh
15/09/2021 08:05:25 - Running init script the 1st time Primary PostgreSql container is created...
```

And looking in the logs that you have provided, it looks like your custom configMap is not used by Primary Pod.

In which order did you create the resources?
For me it was:
- create my custom configmap
- create secret
- create kubegres yaml

**Comment by kahunacohen** [comment]
Hmm, still not working for me. Again, here's kubegres manifest:

```yaml
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:

   replicas: 3
   image: postgres:13.2

   database:
      size: 200Mi
   customConfig: mypostgres-conf
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
```

conf manifest:

```yaml
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:

   replicas: 3
   image: postgres:13.2

   database:
      size: 200Mi
   customConfig: mypostgres-conf
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: replicationUserPassword
```

Order of manifest creation (I am using skaffold):

```bash
...
 - configmap/web-configmap created
 - deployment.apps/web-deployment created
 - service/web-service created
 - cronjob.batch/print-hello created
 - configmap/mypostgres-conf created
 - secret/mypostgres-secret created
 - kubegres.kubegres.reactive-tech.io/mypostgres created
 ...
```
I terminate all pods by doing `skaffold delete` and confirm they don't exist. Then:

```bash
$ kubectl logs mypostgres-1-0

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-09-15 10:04:18.701 GMT [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
2021-09-15 10:04:18.701 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-09-15 10:04:18.701 GMT [1] LOG:  listening on IPv6 address "::", port 5432
2021-09-15 10:04:18.702 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-09-15 10:04:18.705 GMT [26] LOG:  database system was shut down at 2021-09-15 10:04:11 GMT
2021-09-15 10:04:18.709 GMT [1] LOG:  database system is ready to accept connections
```
