### ISSUE TITLE
Service Type in CR

### ISSUE THREAD

**Issue by Seljuke** [reactive-tech/kubegres#46]
Hi,

It would be great to have a way to change primary and replica service types from default ClusterIP to LoadBalancer and NodePort. Right now I'm using nginx ingress TCP loadbalancing but it adds complexity and dependency to ingress pod.

Something like below would be great;

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:

   replicas: 3
   image: postgres:13.2

  service:
    primary:
      type: LoadBalancer
    replica:
      type: NodePort
      nodePort: 30543

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: mypostgres-secret
```

If method at #44 wouldn't require UID of original service I could create a helm chart that can create external facing service with pre-install hook.
