### ISSUE TITLE
Allow kubegres cluster to run on secure Kubernetes environments (Pod security policies)

### ISSUE THREAD

**Issue by teknologista** [reactive-tech/kubegres#52]
Hi,

First thanks for your work on a Postgres cluster Kubernetes Operator.

We are deploying Kubernetes clusters in a secure by design manner using Rancher's RKE2 (aka RKE Government v1.20.11+rke2r2)

This creates a cluster with a hardened Pod Security policy which forbids, among others pods, from running as root.

This implies the workloads must have security context defined with at least these to settings (1001 is the postgres image running user):

```
securityContext:
  - runAsNonRoot: true
  - runAsUser: 1001
```

Looking at the baseConfigMap I also see you do some `chown postgres:postgres ` when copying data from primary to replicas. I guess these would fail with these settings.

In "enterprise" setups this is actually not needed as CSI provisioned Pas do belong to the pod running user AFAIK.

While I understand this level of security is not needed by everyone and some users want to be able to run things in smaller clusters where security is not mandatory, I was wondering if it was possible to have some boolean flag in the CR yaml (ie: hardened : true/false) that would allow the workload to run in hardened PSP clusters.

This flag would basically use an alternate baseConfigMap with no chown commands and the added securityContext to the statefulSet.

FYI, right now we run a single node not replicated postgres server with the above securityContext with no issues whatsoever.

Let me know what you think about this.

many thanks,

Eric

**Comment by alex-arica** [comment]
Thank you for the details that you have provided. 

I added this feature in the active backlog. 

In regards to the features requested by the Open Source community, I dedicate one continuous week per month to Kubegres. It is usually the last week of each month. However, for companies paying support, we implement new features as soon as possible.

Consequently, I will be able to look at this feature from the 25 October. If meanwhile there is someone else in the community willing to help with this change, I can review a PR as soon as possible.

**Comment by ylck** [comment]
Hi,

I think I can update this function
CR YAML does it look like this?
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default

spec:
   replicas: 3
   image: postgres:13.2
   hardened : true/false
   database:
      size: 200Mi
```

Also `chown -R postgres:postgres $PGDATA;` needs to be changed to 

```
if [ $UID == 0 ] 
then
chown -R postgres:postgres $PGDATA; 
fi
```

@alex-arica @teknologista

**Comment by teknologista** [comment]
@ylck @alex-arica , adding the full securityContext is even better because it allows further customisations.
As per analysis I am willing to test the PR on our RKE2 hardened clusters
Many thanks again!

**Comment by alex-arica** [comment]
@ylck It seems like your last message has missing text. The last sentence I can see is " I will further modify the ..." and there is nothing else.

@teknologista I released a "beta" version in the main branch with the features that you suggested. To install it and test it please run: 
```
kubectl apply -f  https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

I tested it locally with the following config in the YAML:
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:
...
 securityContext:
   runAsNonRoot: true
   runAsUser: 999
...

```

Please let me know if it works for you. Once you confirmed it, I will release a new version of Kubegres.

**Comment by ylck** [comment]
@alex-arica  Run and fix test case took a long time, if I need to submit a test case

**Comment by alex-arica** [comment]
@ylck It seems like your last message had missing text. I can see is:  " I will further modify the ..." 
and then nothing else. I think your last message did not post correctly.

If you wrote test cases, thank you for your help. If you would like me to review them, please create a PR and I will review them ASAP.

**Comment by ylck** [comment]
@alex-arica  ok ，`SecurityContextSpecEnforcer.go ` Is this file still needed?
I see that you only configured it when CreatorFromTemplate.go was created

**Comment by alex-arica** [comment]
Yes the file SecurityContextSpecEnforcer.go is required. I did not implement it yet. 
If you did that's great! It will help. Thank you :)

**Comment by alex-arica** [comment]
@ylck Thank you for the additional code changes that you submitted.
I merged them into the main branch.

**Comment by alex-arica** [comment]
@teknologista  Do you think you could help by testing this change today? I am planning to release it Wednesday.

I released a "beta" version in the main branch with the features that you suggested. To install it and test it please run: 
```
kubectl apply -f  https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

I tested it locally with the following config in the YAML:
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:
...
 securityContext:
   runAsNonRoot: true
   runAsUser: 999
...

```

Please let me know if it works for you with your parameters. Once you confirmed it, I will release a new version of Kubegres.
