### ISSUE TITLE
Kubegres complains about missing value for topologyKey when using podAntiAffinity requiredDuringSchedulingIgnoredDuringExecution

### ISSUE THREAD

**Issue by joes** [reactive-tech/kubegres#56]
Hi!

I attempted to use `requiredDuringSchedulingIgnoredDuringExecution` as `podAntiAffinity`:

```yaml
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: example-postgres-db
  namespace: example-db

spec:
  replicas: 3
  # use latest-tag to force imagePullPolicy: always
  image: gitlab.example.se:5050/containers/container-images/postgres/postgres:latest
  imagePullSecrets:
    - name: gitlab-example-se-regcred

  scheduler:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: example.se/postgres-db-node
              operator: In
              values:
              - example-postgres-db
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                        - example-postgres-db
                topologyKey: "kubernetes.io/hostname"

  database:
    size: 10Gi

  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-db-admin-secret
          key: superUserPassword

    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-db-admin-secret
          key: replicationUserPassword
```

However, I receive the following error if I apply the above specification:
```
The Kubegres "example-postgres-db" is invalid: spec.scheduler.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution.topologyKey: Required value
```

As far as I can tell this error message is not correct since I have defined `topologyKey: "kubernetes.io/hostname"`.

If I change `requiredDuringSchedulingIgnoredDuringExecution` to `preferredDuringSchedulingIgnoredDuringExecution` the configuration can be applied just fine (without errors).

Thank you for making kubegres and I look forward to getting it up and running!
