### ISSUE TITLE
Lots of statefulsets?

### ISSUE THREAD

**Issue by joes** [reactive-tech/kubegres#57]
Hi,

I seem to get a lot of "singleton" statefulsets, i.e. a lot of statefulsets that define `spec.replicas: 1` for each replica defined in the kubegres-resource.  Or, in other words, each kubegres replica results in one statefulset that manage exactly one pod/replica. Is this intended (as designed) or a bug? 

----

To exemplify, `spec.replicas: 3` in the kubegres-resource, here:

```yaml
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: example-postgres-db
  namespace: db

spec:
  replicas: 3
```

Results in these three statefulsets (`kubectl get statefulset.apps -n db`):

```plain
NAME                         READY   AGE
example-postgres-db-1   1/1     28m
example-postgres-db-2   1/1     27m
example-postgres-db-3   1/1     27m
```

Each of the above statefulsets are defined with `spec.replicas: 1`.
