### ISSUE TITLE
Configure SSL

### ISSUE THREAD

**Issue by pgvirtuoso** [reactive-tech/kubegres#58]
I mounted a TLS secret successfully. But, I can't set up permissions for postgres to access the file. Is there any way to set fsGroup? Also, is there any way to set init containers?

**Comment by alex-arica** [comment]
Thank you for your message.

Could you please share the contents of the Kubegres configurations resources that you have created (ConfigMap, YAML of kind Kubegres, ...) and also the error message that Postgres displays when trying to access to the file?

**Comment by pgvirtuoso** [comment]
I just did. Same error:
`apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: wpg-kubegres
  namespace: watcher

spec:
  volume:
    volumes:
    - name: certs
      secret:
        secretName: wpg-sdstage01-kcftech-com-tls
        defaultMode: 0644
    volumeMounts:
    - mountPath: /var/lib/postgresql/certs
      name: certs
  replicas: 3
  image: postgres:14

  customConfig: wpg-conf
  database:
     size: 75Gi

  env:
     - name: POSTGRES_PASSWORD
       valueFrom:
          secretKeyRef:
             name: wpg-secret
             key: superUserPassword

     - name: POSTGRES_REPLICATION_PASSWORD
       valueFrom:
          secretKeyRef:
             name: wpg-secret
             key: replicationUserPassword`

**Comment by alex-arica** [comment]
Thank you. 

The file tls.crt is a symlink pointing to a file in the folder data.

Could you please do a ```ls -a``` on the file located in the data folder?

**Comment by alex-arica** [comment]
Could you please move the certificate file to that folder?

**Comment by pgvirtuoso** [comment]
PostgreSQL won't start; the pods get stuck in CrashLoopBackOff.

**Comment by pgvirtuoso** [comment]
Ok, understood. Thank you!

**Comment by pgvirtuoso** [comment]
That would be awesome! ty!

**Comment by pgvirtuoso** [comment]
Sorry for the delay. I tested defaultMode 644 and got the following error.
`ubuntu@ip-10-0-1-219:~$ kubectl -n pgvirtuoso logs -f -l app=ivdb

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-10-31 00:02:25.250 GMT [1] FATAL:  private key file "/var/lib/postgresql/data/certs/tls.key" has group or world access
2021-10-31 00:02:25.250 GMT [1] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
2021-10-31 00:02:25.250 GMT [1] LOG:  database system is shut down
`
I changed to 640 and got this error:
`ubuntu@ip-10-0-1-219:~$ kubectl -n pgvirtuoso logs -f -l app=ivdb

PostgreSQL Database directory appears to contain a database; Skipping initialization

2021-10-31 00:06:24.820 GMT [1] FATAL:  could not load server certificate file "/var/lib/postgresql/data/certs/tls.crt": Permission denied
2021-10-31 00:06:24.820 GMT [1] LOG:  database system is shut down
`
Is there an option to deploy init container?

**Comment by alex-arica** [comment]
There is no option to deploy init container. I am happy to review a PR if a developer from the community would like to add this feature.

I released a "beta" version in the main branch which allows to specify the field "securityContext" . To install it and test it please run: 
```
kubectl apply -f  https://raw.githubusercontent.com/reactive-tech/kubegres/main/kubegres.yaml
```

I tested it locally with the following config in the YAML:
```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:
...
 securityContext:
   runAsNonRoot: true
   runAsUser: 999
...

```
Under securityContext, you can specify fsGroup as well.

**Comment by alex-arica** [comment]
What would you use as a code/script if it was possible to have a deploy init container?

**Comment by pgvirtuoso** [comment]
I was thinking of a bash script to change file ownership and properties. AKA, chmod and chown.

**Comment by pgvirtuoso** [comment]
BTW, it worked!!!! Thank you! SSL is on. (I used cert-manager with let's encrypt certificate and connected with full verification)

**Comment by alex-arica** [comment]
Nice one! 

Thank you for sharing all the details which allowed you to get there. 

I am closing this issue.

**Comment by alex-arica** [comment]
Note that Kubegres version 1.13 is available with the support for the new field `securityContext`.

Please see the release page: 
https://github.com/reactive-tech/kubegres/releases/tag/v1.13

I updated the documentation by adding details about the new field 'securityContext':
https://www.kubegres.io/doc/properties-explained.html

To install Kubegres 1.13, please run:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.13/kubegres.yaml
```

**Comment by pgvirtuoso** [comment]
Thank you!!!!

**Comment by movitto** [comment]
To get this working locally we had to specify the following in our kubegres config;

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:
   replicas: 3
   image: postgres:14.1
   database:
      size: 10Gi
   customConfig: mypostgres-conf
   securityContext:
     fsGroup: 999
   volume:
     volumeMounts:
       - mountPath: "/mypostgres/.postgresql"
         name: mypostgres-server-tls
         readOnly: true
     volumes:
       - name: mypostgres-server-tls
         secret:
           secretName: mypostgres-server-tls
           defaultMode: 0400
   env:
     - name: POSTGRES_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mypostgres-secret
           key: superUserPassword
     - name: POSTGRES_REPLICATION_PASSWORD
       valueFrom:
         secretKeyRef:
           name: mypostgres-secret
           key: replicationUserPassword
```

Of particular importance is that **only** fsGroup was specified to the securityContext as specifying runAsNonRoot / runAsUser resulted in the following error:

```
mkdir: cannot create directory ‘/var/lib/postgresql/data/pgdata’: Permission denied
```

Also note **defaultMode** is specified as volume parameter, omitting this results in:

```
2022-01-06 21:15:59.609 GMT [1] FATAL:  private key file "/mypostgres/.postgresql/tls.key" has group or world access
2022-01-06 21:15:59.609 GMT [1] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
```

Finally if defaultMode is specified but fsGroup is **not** specified, you will get the following error:

```
2022-01-06 21:16:47.837 GMT [1] FATAL:  could not load server certificate file "/mypostgres/.postgresql/tls.crt": Permission denied
```

Only through the combination specified above were we able to get it working. We will elaborate more momentarily in another issue (feature request to add ssl option)
