### ISSUE TITLE
Overwrite Readiness and Liveness config

### ISSUE THREAD

**Issue by owenchenxy** [reactive-tech/kubegres#72]
Hi, alex,

I've encounterd one problem that the pgserver pods was reporting readiness/liveness probe failed. And this lead to frequent failovers. I try to login to the shell of the pod and try executing the readiness/liveness probe command: 

`sh -c exec pg_isready -U postgres -h $POD_IP`

it always succeed with out any error. I guess it might failed only occassionally due to timeout probably. So I use 
`kubectl edit sts pgserver-x-x` 
to set a larger number for the timeout value of Readiness/Liveness probe. This seemed to work out fine, I can see it came back  ready since the change had been made, and it's stilling working fine now.

However, I went through the docs but didn't find a way to overwrite these configs, Could you support overwriting the Readiness/Liveness configuration for the statefulsets?

**Comment by owenchenxy** [comment]
I opened an PR for this issue:
https://github.com/reactive-tech/kubegres/pull/75

**Comment by alex-arica** [comment]
Hi Owen,

Thank you for submitting a PR. I am going to review it this Tuesday and let you know on the same day.

**Comment by alex-arica** [comment]
I added a comment about your PR, under the "Conversation" tab.

**Comment by owenchenxy** [comment]
> I added a comment about your PR, under the "Conversation" tab.

I've updated the PR. It should be ready to merge now. Please check.

**Comment by alex-arica** [comment]
Thank you! 
I merged your changes in the main branch. 
This Thursday, I will run some tests locally and if everything is working fine, Kubegres version 1.15 will be released in prod with your changes.

**Comment by owenchenxy** [comment]
Thanks

**Comment by alex-arica** [comment]
@owenchenxy  Kubegres version 1.15 is available with the changes that you implemented. 

Please see the release page: 
https://github.com/reactive-tech/kubegres/releases/tag/v1.15

Thank you @owenchenxy for reporting and implementing this feature!

To install Kubegres 1.15, please run:
```
kubectl apply -f https://raw.githubusercontent.com/reactive-tech/kubegres/v1.15/kubegres.yaml
```

I am closing this issue.

**Comment by alex-arica** [comment]
@owenchenxy I made few minor changes to your initial commit.

I moved the properties 'livenessProbe' and 'readinessProbe' under the property 'probe' as follows:

```
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: mypostgres
  namespace: default
spec:
...

  probe:
      
     livenessProbe:
        exec:
          command:
            - sh
            - -c
            - exec pg_isready -U postgres -h $POD_IP
        failureThreshold: 10
        initialDelaySeconds: 60
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 15

      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - exec pg_isready -U postgres -h $POD_IP
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        timeoutSeconds: 3
```

In the StatefulSets, I slightly increased the values in the default `livenessProbe` and `readinessProbe`, as follows:

```
         livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U postgres -h $POD_IP
            failureThreshold: 10
            initialDelaySeconds: 60
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 15

         readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U postgres -h $POD_IP
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
```
