### ISSUE TITLE
Feature Request: Service targeting both master & replicas

### ISSUE THREAD

**Issue by LanDinh** [reactive-tech/kubegres#74]
Thanks a ton for this project! I have a feature request :)

According to the documentation, the following services get created:

* `<service>` pointing to the master
* `<service>-replica` pointing to the replicas

I however have the following use case: There are many read, but very, very few write operations. So I could of course simply use <service>-replica for the read operations to have multiple instances serving read-only data, but that would mean that there's one idle instance - the current master.

In my case, I absolutely don't care who ends up serving read requests, but I want to save resources by distributing these requests among *all* instances that can serve them - meaning that I would need a service targeting both the master and the replicas :)

I hope that this feature will make it in at some point :)

**Comment by alex-arica** [comment]
Thank you for your message. 

It is currently possible to manually create a Service to target the primary and replicas pods, as follows:

```
apiVersion: v1
kind: Service
metadata:
  name: my-postgres
  namespace: default
  labels:
    app: my-postgres
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5432
  selector:
    app: my-postgres
```

Please let me know if that helps.
