### ISSUE TITLE
Question: New statefulsets - how to get back to the old ones?

### ISSUE THREAD

**Issue by joes** [reactive-tech/kubegres#88]
I am trying to contain the statefulsets to exactly three (and no more) each running on their own node using:

```yaml
spec:
  replicas: 3
  # use latest-tag to force imagePullPolicy: always
  image: myorg.com/postgres/postgres:13.2-main-cb70d28e
  imagePullSecrets:
    - name: registry-host-regcred

  scheduler:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: postgres-db-node
              operator: In
              values:
              - myorg-postgres-db
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                - myorg-postgres-db
          topologyKey: "kubernetes.io/hostname"
```

Once applied three statefulsets with indices 1, 2 and 3 were created and each was running on their own node:

- myorg-postgres-db-1-0
- myorg-postgres-db-2-0
- myorg-postgres-db-3-0

However, after promoting another pod the previous "master" got replaced by a new statefulset with index 4 so that I then had statefulsets 1, 2 and 4:

- myorg-postgres-db-1-0
- myorg-postgres-db-2-0
- myorg-postgres-db-4-0

And, finally, after doing some maintenance on the nodes which required me to drain and uncordon nodes index 1 and 2 got replaced with two new statefulsets with indices 5 and 6 so that I now have:

- myorg-postgres-db-4-0
- myorg-postgres-db-5-0
- myorg-postgres-db-6-0

Is it possible to get rid of 4, 5 and 6 and get back to the initial state with three statefulsets numbered 1, 2 and 3 like this?

- myorg-postgres-db-1-0
- myorg-postgres-db-2-0
- myorg-postgres-db-3-0

Is this possible?

**Comment by anthonator** [comment]
Just out of curiosity. Assuming everything is working why do you want StatefulSets 1, 2 and 3 back?

**Comment by alex-arica** [comment]
If you are doing some maintenance on the Kubernetes nodes, it is possible to disable the automatic failover process of Kubegres by setting the property 'spec.failover.isDisabled = true'

If this flag is true, Kubegres will not not trigger the failover process when the primary StatefulSet is unhealthy/unavailable.

More details:
https://www.kubegres.io/doc/properties-explained.html#spec_failover

Once a failover is triggered and is completed, it is not possible to rollback to the previous primary StatefulSet (in your case it was StatefulSet 1).

**Comment by joes** [comment]
If a node goes down in an ”unscheduled” manner do I need to do some housekeeping wrt to any persistent volumes with left-over data?

It would however be great if the operator could be configured to only spawn new statefulsets if the pre-existing one could not be made to resume after ”x” retries.  When a node goes down it might as well continue using the ”old” statefulsets since there really was nothing wrong with it (it was just that the node restarted). I imagine that it would be quicker to get back up and running since an ”old” statefulset would not have to retrieve a full copy of the current database from another statefulset. Or does the new statefulset ”inherit” the persistent data from the statefulset it replaced?

**Comment by joes** [comment]
Why would I want to get them back @anthonator?

Because I would like to think that a system should be returned to its ”normal” state as soon as possible after failover. I believe that if the ”normal” state is easy to reason about (three statefulsets, 1-3) it is also simpler to detect if the system is in an anomalous/erroneous state.

**Comment by alex-arica** [comment]
@joes thank you for your message.

One feature that could be implemented based on your feedback is a new field in the Kubegres YAML which allows to set the number of seconds Kubegres should wait for before triggering a failover if a Primary StatefulSet is not available. For example, if you set that field to 30 seconds, once Kubegres has detected that a StatefulSet is not available, it would wait 30 seconds before promoting a Replica as a Primary. If you restart a StatefulSet or a Pod, this restart would be take less than 30 seconds and the Pod would be available before then, so that feature might help. 

Currently, Kubegres reacts in less than 5 seconds.

`If a node goes down in an ”unscheduled” manner do I need to do some housekeeping wrt to any persistent volumes with left-over data?`
=> Yes currently you will have to manually delete the PVC which are not deleted for security reasons. A feature is planned with #20 to give the option to let Kubegres to remove a PVC associated to an unscheduled StatefulSet.

` When a node goes down it might as well continue using the ”old” statefulset since there really was nothing wrong with it (it was just that the node restarted)`
=> Kubegres does not know the reason behind why a node or a statefulset is not available. The Kubernetes API provided by [Kubebuilder](https://book.kubebuilder.io/) to the Kubegres operator has the following information:
- whether a node is available
- whether Statefulsets or pod are deployed
- whether Statefulsets and PosgreSql pods are running
- whether PosgreSql pods are healthy based on the declaration of the binary `pg_isready` in `LivenessProbe` and `readinessProbe` in each Statefulset YAML.

For this reason Kubegres does not know why the StatefulSet is reported as not available and it takes the action to isolate it and promote a replica StatefulSet as primary to avoid downtime.

`does the new statefulset ”inherit” the persistent data from the statefulset it replaced?`
=> We do not reuse the PVC of a StatefulSet which was replaced. As we do not know whether the PVC has corrupted data causing the unavailability of the PosgreSql pod.

`I would like to think that a system should be returned to its ”normal” state as soon as possible after failover. I believe that if the ”normal” state is easy to reason about (three statefulsets, 1-3) `
=> A normal state is not defined by the number assigned to each StatefulSet, if it is what you meant. The normality is about a Primary PostgreSql pod to be always available and one or many Replica pods to be also always available.

**Comment by Y0ngg4n** [comment]
Ok i have a question. When i disable failover... and my primary pod fails, will it promote one of my replicas as primary? or does this only works when creating a new replica set?

**Comment by lentzi90** [comment]
> One feature that could be implemented based on your feedback is a new field in the Kubegres YAML which allows to set the number of seconds Kubegres should wait for before triggering a failover if a Primary StatefulSet is not available. For example, if you set that field to 30 seconds, once Kubegres has detected that a StatefulSet is not available, it would wait 30 seconds before promoting a Replica as a Primary. If you restart a StatefulSet or a Pod, this restart would be take less than 30 seconds and the Pod would be available before then, so that feature might help.
> 
> Currently, Kubegres reacts in less than 5 seconds.

This sounds useful to me! But I wonder why we would need a new field for it? I was thinking that probe (liveness/readiness) was used for this. Are the 5 seconds after the livenessprobe has indicated that it has failed or is it determined in some other way?

What I'm after is basically to be able to restart Nodes in a controlled manner without having to clean up old PVCs afterwards. So I want kubegres to wait for say 5 mins and if everything is back then just continue as normal.

Automatically deleting the PVCs (as suggested in https://github.com/reactive-tech/kubegres/issues/20) could be a workaround, but I would prefer actually to avoid the extra churn.

**Comment by joeywang** [comment]
I haven't find a way to change the index in kubegres, it seems like relying on the status `last_index`

But what we can do is to clone the PVC to something like `pg14-1-0` and do a fresh install it will pick up the existing pvc you just cloned.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: clone-of-pvc-1
    namespace: myns
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: cloning
  resources:
    requests:
      storage: 5Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: pvc-1
```
